var annotated_dup =
[
    [ "com", null, [
      [ "systemic", null, [
        [ "bluetoothle", "namespacecom_1_1systemic_1_1bluetoothle.html", [
          [ "Peripheral", "classcom_1_1systemic_1_1bluetoothle_1_1_peripheral.html", "classcom_1_1systemic_1_1bluetoothle_1_1_peripheral" ],
          [ "Scanner", "classcom_1_1systemic_1_1bluetoothle_1_1_scanner.html", "classcom_1_1systemic_1_1bluetoothle_1_1_scanner" ]
        ] ]
      ] ]
    ] ],
    [ "Systemic", "namespace_systemic.html", [
      [ "BluetoothLE", "namespace_systemic_1_1_bluetooth_l_e.html", [
        [ "Characteristic", "class_systemic_1_1_bluetooth_l_e_1_1_characteristic.html", "class_systemic_1_1_bluetooth_l_e_1_1_characteristic" ],
        [ "Peripheral", "class_systemic_1_1_bluetooth_l_e_1_1_peripheral.html", "class_systemic_1_1_bluetooth_l_e_1_1_peripheral" ],
        [ "ManufacturerData", "class_systemic_1_1_bluetooth_l_e_1_1_manufacturer_data.html", "class_systemic_1_1_bluetooth_l_e_1_1_manufacturer_data" ],
        [ "AdvertisementData", "class_systemic_1_1_bluetooth_l_e_1_1_advertisement_data.html", "class_systemic_1_1_bluetooth_l_e_1_1_advertisement_data" ],
        [ "ScannedPeripheral", "class_systemic_1_1_bluetooth_l_e_1_1_scanned_peripheral.html", "class_systemic_1_1_bluetooth_l_e_1_1_scanned_peripheral" ],
        [ "Scanner", "class_systemic_1_1_bluetooth_l_e_1_1_scanner.html", "class_systemic_1_1_bluetooth_l_e_1_1_scanner" ],
        [ "Service", "class_systemic_1_1_bluetooth_l_e_1_1_service.html", "class_systemic_1_1_bluetooth_l_e_1_1_service" ]
      ] ],
      [ "Unity", "namespace_systemic_1_1_unity.html", [
        [ "BluetoothLE", "namespace_systemic_1_1_unity_1_1_bluetooth_l_e.html", [
          [ "BleUuid", "class_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_ble_uuid.html", "class_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_ble_uuid" ],
          [ "Central", "class_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_central.html", "class_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_central" ],
          [ "NativePeripheralHandle", "struct_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_native_peripheral_handle.html", "struct_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_native_peripheral_handle" ],
          [ "NativeInterface", "class_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_native_interface.html", "class_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_native_interface" ],
          [ "RequestEnumerator", "class_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_request_enumerator.html", "class_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_request_enumerator" ],
          [ "ScannedPeripheral", "class_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_scanned_peripheral.html", "class_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_scanned_peripheral" ],
          [ "ValueRequestEnumerator", "class_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_value_request_enumerator.html", "class_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_value_request_enumerator" ]
        ] ],
        [ "Examples", "namespace_systemic_1_1_unity_1_1_examples.html", [
          [ "BleConsole", "class_systemic_1_1_unity_1_1_examples_1_1_ble_console.html", null ],
          [ "BleController", "class_systemic_1_1_unity_1_1_examples_1_1_ble_controller.html", "class_systemic_1_1_unity_1_1_examples_1_1_ble_controller" ],
          [ "PixelController", "class_systemic_1_1_unity_1_1_examples_1_1_pixel_controller.html", "class_systemic_1_1_unity_1_1_examples_1_1_pixel_controller" ],
          [ "PixelsDemo", "class_systemic_1_1_unity_1_1_examples_1_1_pixels_demo.html", null ],
          [ "UILogToText", "class_systemic_1_1_unity_1_1_examples_1_1_u_i_log_to_text.html", "class_systemic_1_1_unity_1_1_examples_1_1_u_i_log_to_text" ],
          [ "UIPixelPanel", "class_systemic_1_1_unity_1_1_examples_1_1_u_i_pixel_panel.html", "class_systemic_1_1_unity_1_1_examples_1_1_u_i_pixel_panel" ],
          [ "UIUpdateScanToggle", "class_systemic_1_1_unity_1_1_examples_1_1_u_i_update_scan_toggle.html", null ]
        ] ],
        [ "Pixels", "namespace_systemic_1_1_unity_1_1_pixels.html", [
          [ "Animations", "namespace_systemic_1_1_unity_1_1_pixels_1_1_animations.html", [
            [ "AnimationFadeCandy", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_fade_candy.html", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_fade_candy" ],
            [ "AnimationInstanceFadeCandy", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_instance_fade_candy.html", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_instance_fade_candy" ],
            [ "AnimationGradient", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_gradient.html", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_gradient" ],
            [ "AnimationInstanceGradient", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_instance_gradient.html", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_instance_gradient" ],
            [ "Track", "struct_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_track.html", "struct_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_track" ],
            [ "AnimationGradientPattern", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_gradient_pattern.html", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_gradient_pattern" ],
            [ "AnimationInstanceGradientPattern", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_instance_gradient_pattern.html", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_instance_gradient_pattern" ],
            [ "AnimationInstance", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_instance.html", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_instance" ],
            [ "RGBTrack", "struct_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_r_g_b_track.html", "struct_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_r_g_b_track" ],
            [ "AnimationKeyframed", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_keyframed.html", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_keyframed" ],
            [ "AnimationInstanceKeyframed", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_instance_keyframed.html", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_instance_keyframed" ],
            [ "AnimationRainbow", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_rainbow.html", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_rainbow" ],
            [ "AnimationInstanceRainbow", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_instance_rainbow.html", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_instance_rainbow" ],
            [ "AnimationSimple", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_simple.html", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_simple" ],
            [ "AnimationInstanceSimple", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_instance_simple.html", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_instance_simple" ],
            [ "DataSet", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_data_set.html", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_data_set" ],
            [ "IAnimation", "interface_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_i_animation.html", "interface_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_i_animation" ],
            [ "RGBKeyframe", "struct_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_r_g_b_keyframe.html", "struct_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_r_g_b_keyframe" ],
            [ "Keyframe", "struct_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_keyframe.html", "struct_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_keyframe" ]
          ] ],
          [ "Behaviors", "namespace_systemic_1_1_unity_1_1_pixels_1_1_behaviors.html", [
            [ "IAction", "interface_systemic_1_1_unity_1_1_pixels_1_1_behaviors_1_1_i_action.html", "interface_systemic_1_1_unity_1_1_pixels_1_1_behaviors_1_1_i_action" ],
            [ "ActionPlayAnimation", "class_systemic_1_1_unity_1_1_pixels_1_1_behaviors_1_1_action_play_animation.html", "class_systemic_1_1_unity_1_1_pixels_1_1_behaviors_1_1_action_play_animation" ],
            [ "ActionPlayAudioClip", "class_systemic_1_1_unity_1_1_pixels_1_1_behaviors_1_1_action_play_audio_clip.html", "class_systemic_1_1_unity_1_1_pixels_1_1_behaviors_1_1_action_play_audio_clip" ],
            [ "Behavior", "class_systemic_1_1_unity_1_1_pixels_1_1_behaviors_1_1_behavior.html", "class_systemic_1_1_unity_1_1_pixels_1_1_behaviors_1_1_behavior" ],
            [ "ICondition", "interface_systemic_1_1_unity_1_1_pixels_1_1_behaviors_1_1_i_condition.html", "interface_systemic_1_1_unity_1_1_pixels_1_1_behaviors_1_1_i_condition" ],
            [ "ConditionIdle", "class_systemic_1_1_unity_1_1_pixels_1_1_behaviors_1_1_condition_idle.html", "class_systemic_1_1_unity_1_1_pixels_1_1_behaviors_1_1_condition_idle" ],
            [ "ConditionHandling", "class_systemic_1_1_unity_1_1_pixels_1_1_behaviors_1_1_condition_handling.html", "class_systemic_1_1_unity_1_1_pixels_1_1_behaviors_1_1_condition_handling" ],
            [ "ConditionRolling", "class_systemic_1_1_unity_1_1_pixels_1_1_behaviors_1_1_condition_rolling.html", "class_systemic_1_1_unity_1_1_pixels_1_1_behaviors_1_1_condition_rolling" ],
            [ "ConditionCrooked", "class_systemic_1_1_unity_1_1_pixels_1_1_behaviors_1_1_condition_crooked.html", "class_systemic_1_1_unity_1_1_pixels_1_1_behaviors_1_1_condition_crooked" ],
            [ "ConditionFaceCompare", "class_systemic_1_1_unity_1_1_pixels_1_1_behaviors_1_1_condition_face_compare.html", "class_systemic_1_1_unity_1_1_pixels_1_1_behaviors_1_1_condition_face_compare" ],
            [ "ConditionHelloGoodbye", "class_systemic_1_1_unity_1_1_pixels_1_1_behaviors_1_1_condition_hello_goodbye.html", "class_systemic_1_1_unity_1_1_pixels_1_1_behaviors_1_1_condition_hello_goodbye" ],
            [ "ConditionConnectionState", "class_systemic_1_1_unity_1_1_pixels_1_1_behaviors_1_1_condition_connection_state.html", "class_systemic_1_1_unity_1_1_pixels_1_1_behaviors_1_1_condition_connection_state" ],
            [ "ConditionBatteryState", "class_systemic_1_1_unity_1_1_pixels_1_1_behaviors_1_1_condition_battery_state.html", "class_systemic_1_1_unity_1_1_pixels_1_1_behaviors_1_1_condition_battery_state" ],
            [ "Rule", "class_systemic_1_1_unity_1_1_pixels_1_1_behaviors_1_1_rule.html", "class_systemic_1_1_unity_1_1_pixels_1_1_behaviors_1_1_rule" ]
          ] ],
          [ "Messages", "namespace_systemic_1_1_unity_1_1_pixels_1_1_messages.html", [
            [ "AccelFrame", "struct_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_accel_frame.html", "struct_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_accel_frame" ],
            [ "PixelMessageMarshaling", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_pixel_message_marshaling.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_pixel_message_marshaling" ],
            [ "IPixelMessage", "interface_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_i_pixel_message.html", "interface_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_i_pixel_message" ],
            [ "WhoAreYou", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_who_are_you.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_who_are_you" ],
            [ "IAmADieMarshaledData", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_i_am_a_die_marshaled_data.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_i_am_a_die_marshaled_data" ],
            [ "IAmADie", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_i_am_a_die.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_i_am_a_die" ],
            [ "RollState", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_roll_state.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_roll_state" ],
            [ "AccelerationState", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_acceleration_state.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_acceleration_state" ],
            [ "BulkSetup", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_bulk_setup.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_bulk_setup" ],
            [ "BulkSetupAck", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_bulk_setup_ack.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_bulk_setup_ack" ],
            [ "BulkData", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_bulk_data.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_bulk_data" ],
            [ "BulkDataAck", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_bulk_data_ack.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_bulk_data_ack" ],
            [ "TransferAnimationSet", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_transfer_animation_set.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_transfer_animation_set" ],
            [ "TransferAnimationSetAck", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_transfer_animation_set_ack.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_transfer_animation_set_ack" ],
            [ "TransferAnimationSetFinished", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_transfer_animation_set_finished.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_transfer_animation_set_finished" ],
            [ "TransferTestAnimationSet", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_transfer_test_animation_set.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_transfer_test_animation_set" ],
            [ "TransferTestAnimationSetAck", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_transfer_test_animation_set_ack.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_transfer_test_animation_set_ack" ],
            [ "TransferTestAnimationSetFinished", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_transfer_test_animation_set_finished.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_transfer_test_animation_set_finished" ],
            [ "RequestAnimationSet", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_request_animation_set.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_request_animation_set" ],
            [ "TransferSettings", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_transfer_settings.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_transfer_settings" ],
            [ "TransferSettingsAck", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_transfer_settings_ack.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_transfer_settings_ack" ],
            [ "TransferSettingsFinished", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_transfer_settings_finished.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_transfer_settings_finished" ],
            [ "RequestSettings", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_request_settings.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_request_settings" ],
            [ "RequestTelemetry", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_request_telemetry.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_request_telemetry" ],
            [ "DebugLog", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_debug_log.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_debug_log" ],
            [ "PlayAnimation", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_play_animation.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_play_animation" ],
            [ "PlayAnimationEvent", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_play_animation_event.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_play_animation_event" ],
            [ "StopAnimation", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_stop_animation.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_stop_animation" ],
            [ "PlaySound", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_play_sound.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_play_sound" ],
            [ "RequestRollState", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_request_roll_state.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_request_roll_state" ],
            [ "ProgramDefaultAnimationSet", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_program_default_animation_set.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_program_default_animation_set" ],
            [ "ProgramDefaultAnimSetFinished", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_program_default_anim_set_finished.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_program_default_anim_set_finished" ],
            [ "Blink", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_blink.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_blink" ],
            [ "BlinkFinished", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_blink_finished.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_blink_finished" ],
            [ "RequestDefaultAnimationSetColor", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_request_default_animation_set_color.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_request_default_animation_set_color" ],
            [ "DefaultAnimationSetColor", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_default_animation_set_color.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_default_animation_set_color" ],
            [ "TestBulkSend", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_test_bulk_send.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_test_bulk_send" ],
            [ "TestBulkReceive", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_test_bulk_receive.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_test_bulk_receive" ],
            [ "SetAllLEDsToColor", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_all_l_e_ds_to_color.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_all_l_e_ds_to_color" ],
            [ "RequestBatteryLevel", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_request_battery_level.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_request_battery_level" ],
            [ "BatteryLevel", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_battery_level.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_battery_level" ],
            [ "RequestRssi", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_request_rssi.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_request_rssi" ],
            [ "Rssi", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_rssi.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_rssi" ],
            [ "Calibrate", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_calibrate.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_calibrate" ],
            [ "CalibrateFace", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_calibrate_face.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_calibrate_face" ],
            [ "NotifyUser", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_notify_user.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_notify_user" ],
            [ "NotifyUserAck", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_notify_user_ack.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_notify_user_ack" ],
            [ "TestHardware", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_test_hardware.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_test_hardware" ],
            [ "SetStandardState", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_standard_state.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_standard_state" ],
            [ "SetLEDAnimState", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_l_e_d_anim_state.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_l_e_d_anim_state" ],
            [ "SetBattleState", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_battle_state.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_battle_state" ],
            [ "ProgramDefaultParameters", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_program_default_parameters.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_program_default_parameters" ],
            [ "ProgramDefaultParametersFinished", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_program_default_parameters_finished.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_program_default_parameters_finished" ],
            [ "AttractMode", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_attract_mode.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_attract_mode" ],
            [ "PrintNormals", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_print_normals.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_print_normals" ],
            [ "SetDesignAndColor", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_design_and_color.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_design_and_color" ],
            [ "SetDesignAndColorAck", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_design_and_color_ack.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_design_and_color_ack" ],
            [ "SetCurrentBehavior", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_current_behavior.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_current_behavior" ],
            [ "SetCurrentBehaviorAck", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_current_behavior_ack.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_current_behavior_ack" ],
            [ "SetName", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_name.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_name" ],
            [ "SetNameAck", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_name_ack.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_name_ack" ],
            [ "DebugAnimationController", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_debug_animation_controller.html", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_debug_animation_controller" ]
          ] ],
          [ "BleUuids", "class_systemic_1_1_unity_1_1_pixels_1_1_ble_uuids.html", "class_systemic_1_1_unity_1_1_pixels_1_1_ble_uuids" ],
          [ "ColorUtils", "class_systemic_1_1_unity_1_1_pixels_1_1_color_utils.html", "class_systemic_1_1_unity_1_1_pixels_1_1_color_utils" ],
          [ "DiceBag", "class_systemic_1_1_unity_1_1_pixels_1_1_dice_bag.html", "class_systemic_1_1_unity_1_1_pixels_1_1_dice_bag" ],
          [ "Pixel", "class_systemic_1_1_unity_1_1_pixels_1_1_pixel.html", "class_systemic_1_1_unity_1_1_pixels_1_1_pixel" ]
        ] ]
      ] ]
    ] ],
    [ "SGBleCentralManagerDelegate", "interface_s_g_ble_central_manager_delegate.html", "interface_s_g_ble_central_manager_delegate" ],
    [ "SGBlePeripheralQueue", "interface_s_g_ble_peripheral_queue.html", "interface_s_g_ble_peripheral_queue" ],
    [ "SGBleRequest", "interface_s_g_ble_request.html", "interface_s_g_ble_request" ]
];