var annotated_dup =
[
    [ "ble", null, [
      [ "BleRequestStatus", "classble_1_1_ble_request_status.html", null ],
      [ "CharacteristicProperties", "classble_1_1_characteristic_properties.html", null ],
      [ "ConnectionEvent", "classble_1_1_connection_event.html", null ],
      [ "ConnectionEventReason", "classble_1_1_connection_event_reason.html", null ],
      [ "ScannedPeripheral", "classble_1_1_scanned_peripheral.html", null ]
    ] ],
    [ "com", null, [
      [ "systemic", null, [
        [ "bluetoothle", "namespacecom_1_1systemic_1_1bluetoothle.html", [
          [ "BluetoothState", "classcom_1_1systemic_1_1bluetoothle_1_1_bluetooth_state.html", "classcom_1_1systemic_1_1bluetoothle_1_1_bluetooth_state" ],
          [ "Peripheral", "classcom_1_1systemic_1_1bluetoothle_1_1_peripheral.html", "classcom_1_1systemic_1_1bluetoothle_1_1_peripheral" ],
          [ "Scanner", "classcom_1_1systemic_1_1bluetoothle_1_1_scanner.html", "classcom_1_1systemic_1_1bluetoothle_1_1_scanner" ]
        ] ]
      ] ]
    ] ],
    [ "pixel", null, [
      [ "MessageType", "classpixel_1_1_message_type.html", null ],
      [ "PixelDesignAndColor", "classpixel_1_1_pixel_design_and_color.html", null ],
      [ "PixelRollState", "classpixel_1_1_pixel_roll_state.html", null ],
      [ "PixelUuids", "classpixel_1_1_pixel_uuids.html", null ]
    ] ],
    [ "Systemic", "namespace_systemic.html", [
      [ "BluetoothLE", "namespace_systemic_1_1_bluetooth_l_e.html", [
        [ "AdvertisementData", "class_systemic_1_1_bluetooth_l_e_1_1_advertisement_data.html", "class_systemic_1_1_bluetooth_l_e_1_1_advertisement_data" ],
        [ "Characteristic", "class_systemic_1_1_bluetooth_l_e_1_1_characteristic.html", "class_systemic_1_1_bluetooth_l_e_1_1_characteristic" ],
        [ "ManufacturerData", "class_systemic_1_1_bluetooth_l_e_1_1_manufacturer_data.html", "class_systemic_1_1_bluetooth_l_e_1_1_manufacturer_data" ],
        [ "Peripheral", "class_systemic_1_1_bluetooth_l_e_1_1_peripheral.html", "class_systemic_1_1_bluetooth_l_e_1_1_peripheral" ],
        [ "ScannedPeripheral", "class_systemic_1_1_bluetooth_l_e_1_1_scanned_peripheral.html", "class_systemic_1_1_bluetooth_l_e_1_1_scanned_peripheral" ],
        [ "Scanner", "class_systemic_1_1_bluetooth_l_e_1_1_scanner.html", "class_systemic_1_1_bluetooth_l_e_1_1_scanner" ],
        [ "Service", "class_systemic_1_1_bluetooth_l_e_1_1_service.html", "class_systemic_1_1_bluetooth_l_e_1_1_service" ],
        [ "ServiceData", "class_systemic_1_1_bluetooth_l_e_1_1_service_data.html", "class_systemic_1_1_bluetooth_l_e_1_1_service_data" ]
      ] ],
      [ "Unity", "namespace_systemic_1_1_unity.html", [
        [ "BluetoothLE", "namespace_systemic_1_1_unity_1_1_bluetooth_l_e.html", [
          [ "BleUuid", "class_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_ble_uuid.html", "class_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_ble_uuid" ],
          [ "ManufacturerData", "struct_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_manufacturer_data.html", "struct_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_manufacturer_data" ],
          [ "NativeInterface", "class_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_native_interface.html", "class_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_native_interface" ],
          [ "NativePeripheralHandle", "struct_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_native_peripheral_handle.html", "struct_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_native_peripheral_handle" ],
          [ "RequestEnumerator", "class_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_request_enumerator.html", "class_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_request_enumerator" ],
          [ "ScannedPeripheral", "class_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_scanned_peripheral.html", "class_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_scanned_peripheral" ],
          [ "ServiceData", "struct_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_service_data.html", "struct_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_service_data" ],
          [ "ValueRequestEnumerator", "class_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_value_request_enumerator.html", "class_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_value_request_enumerator" ]
        ] ],
        [ "Examples", "namespace_systemic_1_1_unity_1_1_examples.html", [
          [ "BleConsole", "class_systemic_1_1_unity_1_1_examples_1_1_ble_console.html", null ],
          [ "BleController", "class_systemic_1_1_unity_1_1_examples_1_1_ble_controller.html", "class_systemic_1_1_unity_1_1_examples_1_1_ble_controller" ],
          [ "PixelController", "class_systemic_1_1_unity_1_1_examples_1_1_pixel_controller.html", "class_systemic_1_1_unity_1_1_examples_1_1_pixel_controller" ],
          [ "UILogToText", "class_systemic_1_1_unity_1_1_examples_1_1_u_i_log_to_text.html", "class_systemic_1_1_unity_1_1_examples_1_1_u_i_log_to_text" ],
          [ "UIPixelPanel", "class_systemic_1_1_unity_1_1_examples_1_1_u_i_pixel_panel.html", "class_systemic_1_1_unity_1_1_examples_1_1_u_i_pixel_panel" ],
          [ "UIUpdateScanToggle", "class_systemic_1_1_unity_1_1_examples_1_1_u_i_update_scan_toggle.html", null ]
        ] ],
        [ "Pixels", "namespace_systemic_1_1_unity_1_1_pixels.html", [
          [ "Animations", "namespace_systemic_1_1_unity_1_1_pixels_1_1_animations.html", [
            [ "AnimationFadeCandy", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_fade_candy.html", null ],
            [ "AnimationGradient", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_gradient.html", null ],
            [ "AnimationGradientPattern", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_gradient_pattern.html", null ],
            [ "AnimationInstance", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_instance.html", null ],
            [ "AnimationInstanceFadeCandy", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_instance_fade_candy.html", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_instance_fade_candy" ],
            [ "AnimationInstanceGradient", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_instance_gradient.html", null ],
            [ "AnimationInstanceGradientPattern", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_instance_gradient_pattern.html", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_instance_gradient_pattern" ],
            [ "AnimationInstanceKeyframed", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_instance_keyframed.html", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_instance_keyframed" ],
            [ "AnimationInstanceRainbow", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_instance_rainbow.html", null ],
            [ "AnimationInstanceSimple", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_instance_simple.html", null ],
            [ "AnimationKeyframed", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_keyframed.html", null ],
            [ "AnimationRainbow", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_rainbow.html", null ],
            [ "AnimationSimple", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_animation_simple.html", null ],
            [ "Constants", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_constants.html", null ],
            [ "DataSet", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_data_set.html", "class_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_data_set" ],
            [ "IAnimationPreset", "interface_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_i_animation_preset.html", null ],
            [ "RGBKeyframe", "struct_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_r_g_b_keyframe.html", "struct_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_r_g_b_keyframe" ],
            [ "RGBTrack", "struct_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_r_g_b_track.html", "struct_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_r_g_b_track" ],
            [ "SimpleKeyframe", "struct_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_simple_keyframe.html", "struct_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_simple_keyframe" ],
            [ "Track", "struct_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_track.html", "struct_systemic_1_1_unity_1_1_pixels_1_1_animations_1_1_track" ]
          ] ],
          [ "Messages", "namespace_systemic_1_1_unity_1_1_pixels_1_1_messages.html", [
            [ "AccelerationFrame", "struct_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_acceleration_frame.html", null ],
            [ "BatteryLevel", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_battery_level.html", null ],
            [ "Blink", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_blink.html", null ],
            [ "BlinkAck", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_blink_ack.html", null ],
            [ "BulkData", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_bulk_data.html", null ],
            [ "BulkDataAck", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_bulk_data_ack.html", null ],
            [ "BulkSetup", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_bulk_setup.html", null ],
            [ "BulkSetupAck", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_bulk_setup_ack.html", null ],
            [ "Calibrate", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_calibrate.html", null ],
            [ "CalibrateFace", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_calibrate_face.html", null ],
            [ "CustomDesignAndColorName", "struct_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_custom_design_and_color_name.html", null ],
            [ "DebugLog", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_debug_log.html", null ],
            [ "DefaultAnimationSetColor", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_default_animation_set_color.html", null ],
            [ "DieInfo", "struct_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_die_info.html", null ],
            [ "DieName", "struct_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_die_name.html", null ],
            [ "ExitValidation", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_exit_validation.html", null ],
            [ "IAmADie", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_i_am_a_die.html", null ],
            [ "IAmADieLegacy", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_i_am_a_die_legacy.html", null ],
            [ "IPixelMessage", "interface_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_i_pixel_message.html", null ],
            [ "Marshaling", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_marshaling.html", null ],
            [ "MessageString", "struct_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_message_string.html", null ],
            [ "NotifyUser", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_notify_user.html", null ],
            [ "NotifyUserAck", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_notify_user_ack.html", null ],
            [ "PlayAnimation", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_play_animation.html", null ],
            [ "PlayAnimationEvent", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_play_animation_event.html", null ],
            [ "PlayInstantAnimation", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_play_instant_animation.html", null ],
            [ "PowerOperation", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_power_operation.html", null ],
            [ "ProgramDefaultAnimationSet", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_program_default_animation_set.html", null ],
            [ "ProgramDefaultAnimationSetFinished", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_program_default_animation_set_finished.html", null ],
            [ "ProgramDefaultParameters", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_program_default_parameters.html", null ],
            [ "ProgramDefaultParametersFinished", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_program_default_parameters_finished.html", null ],
            [ "RemoteAction", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_remote_action.html", null ],
            [ "RequestAnimationSet", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_request_animation_set.html", null ],
            [ "RequestBatteryLevel", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_request_battery_level.html", null ],
            [ "RequestDefaultAnimationSetColor", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_request_default_animation_set_color.html", null ],
            [ "RequestRollState", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_request_roll_state.html", null ],
            [ "RequestRssi", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_request_rssi.html", null ],
            [ "RequestSettings", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_request_settings.html", null ],
            [ "RequestTelemetry", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_request_telemetry.html", null ],
            [ "RequestTemperature", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_request_temperature.html", null ],
            [ "RollState", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_roll_state.html", null ],
            [ "Rssi", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_rssi.html", null ],
            [ "SetCurrentBehavior", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_current_behavior.html", null ],
            [ "SetCurrentBehaviorAck", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_current_behavior_ack.html", null ],
            [ "SetDesignAndColor", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_design_and_color.html", null ],
            [ "SetDesignAndColorAck", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_design_and_color_ack.html", null ],
            [ "SetName", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_name.html", null ],
            [ "SetNameAck", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_name_ack.html", null ],
            [ "SettingsInfo", "struct_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_settings_info.html", null ],
            [ "SetTopLevelState", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_top_level_state.html", null ],
            [ "StatusInfo", "struct_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_status_info.html", null ],
            [ "StopAllAnimations", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_stop_all_animations.html", null ],
            [ "StopAnimation", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_stop_animation.html", null ],
            [ "Telemetry", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_telemetry.html", null ],
            [ "Temperature", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_temperature.html", null ],
            [ "TestHardware", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_test_hardware.html", null ],
            [ "TransferAnimationSet", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_transfer_animation_set.html", null ],
            [ "TransferAnimationSetAck", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_transfer_animation_set_ack.html", null ],
            [ "TransferAnimationSetFinished", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_transfer_animation_set_finished.html", null ],
            [ "TransferInstantAnimationSet", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_transfer_instant_animation_set.html", null ],
            [ "TransferInstantAnimationSetAck", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_transfer_instant_animation_set_ack.html", null ],
            [ "TransferInstantAnimationSetFinished", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_transfer_instant_animation_set_finished.html", null ],
            [ "TransferSettings", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_transfer_settings.html", null ],
            [ "TransferSettingsAck", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_transfer_settings_ack.html", null ],
            [ "TransferSettingsFinished", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_transfer_settings_finished.html", null ],
            [ "VersionInfo", "struct_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_version_info.html", null ],
            [ "WhoAreYou", "class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_who_are_you.html", null ]
          ] ],
          [ "Profiles", "namespace_systemic_1_1_unity_1_1_pixels_1_1_profiles.html", [
            [ "ActionPlayAnimation", "class_systemic_1_1_unity_1_1_pixels_1_1_profiles_1_1_action_play_animation.html", null ],
            [ "ActionPlayAudioClip", "class_systemic_1_1_unity_1_1_pixels_1_1_profiles_1_1_action_play_audio_clip.html", null ],
            [ "ConditionBatteryState", "class_systemic_1_1_unity_1_1_pixels_1_1_profiles_1_1_condition_battery_state.html", null ],
            [ "ConditionConnectionState", "class_systemic_1_1_unity_1_1_pixels_1_1_profiles_1_1_condition_connection_state.html", null ],
            [ "ConditionCrooked", "class_systemic_1_1_unity_1_1_pixels_1_1_profiles_1_1_condition_crooked.html", null ],
            [ "ConditionFaceCompare", "class_systemic_1_1_unity_1_1_pixels_1_1_profiles_1_1_condition_face_compare.html", null ],
            [ "ConditionHandling", "class_systemic_1_1_unity_1_1_pixels_1_1_profiles_1_1_condition_handling.html", null ],
            [ "ConditionHelloGoodbye", "class_systemic_1_1_unity_1_1_pixels_1_1_profiles_1_1_condition_hello_goodbye.html", null ],
            [ "ConditionIdle", "class_systemic_1_1_unity_1_1_pixels_1_1_profiles_1_1_condition_idle.html", null ],
            [ "ConditionRolling", "class_systemic_1_1_unity_1_1_pixels_1_1_profiles_1_1_condition_rolling.html", null ],
            [ "IAction", "interface_systemic_1_1_unity_1_1_pixels_1_1_profiles_1_1_i_action.html", null ],
            [ "ICondition", "interface_systemic_1_1_unity_1_1_pixels_1_1_profiles_1_1_i_condition.html", null ],
            [ "Profile", "class_systemic_1_1_unity_1_1_pixels_1_1_profiles_1_1_profile.html", null ],
            [ "Rule", "class_systemic_1_1_unity_1_1_pixels_1_1_profiles_1_1_rule.html", null ]
          ] ],
          [ "ColorUIntUtils", "class_systemic_1_1_unity_1_1_pixels_1_1_color_u_int_utils.html", "class_systemic_1_1_unity_1_1_pixels_1_1_color_u_int_utils" ],
          [ "DiceBag", "class_systemic_1_1_unity_1_1_pixels_1_1_dice_bag.html", "class_systemic_1_1_unity_1_1_pixels_1_1_dice_bag" ],
          [ "DiceUtils", "class_systemic_1_1_unity_1_1_pixels_1_1_dice_utils.html", null ],
          [ "GammaUtils", "class_systemic_1_1_unity_1_1_pixels_1_1_gamma_utils.html", "class_systemic_1_1_unity_1_1_pixels_1_1_gamma_utils" ],
          [ "Pixel", "class_systemic_1_1_unity_1_1_pixels_1_1_pixel.html", "class_systemic_1_1_unity_1_1_pixels_1_1_pixel" ],
          [ "PixelBleUuids", "class_systemic_1_1_unity_1_1_pixels_1_1_pixel_ble_uuids.html", "class_systemic_1_1_unity_1_1_pixels_1_1_pixel_ble_uuids" ]
        ] ]
      ] ]
    ] ],
    [ "SGBleCentralManagerDelegate", "interface_s_g_ble_central_manager_delegate.html", "interface_s_g_ble_central_manager_delegate" ],
    [ "SGBlePeripheralQueue", "interface_s_g_ble_peripheral_queue.html", "interface_s_g_ble_peripheral_queue" ],
    [ "SGBleRequest", "interface_s_g_ble_request.html", "interface_s_g_ble_request" ]
];