var searchData=
[
  ['scannedperipheral_621',['ScannedPeripheral',['../class_systemic_1_1_bluetooth_l_e_1_1_scanned_peripheral.html',1,'Systemic::BluetoothLE::ScannedPeripheral'],['../class_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_scanned_peripheral.html',1,'Systemic.Unity.BluetoothLE.ScannedPeripheral']]],
  ['scanner_622',['Scanner',['../classcom_1_1systemic_1_1bluetoothle_1_1_scanner.html',1,'com.systemic.bluetoothle.Scanner'],['../class_systemic_1_1_bluetooth_l_e_1_1_scanner.html',1,'Systemic::BluetoothLE::Scanner']]],
  ['scannercallback_623',['ScannerCallback',['../interfacecom_1_1systemic_1_1bluetoothle_1_1_scanner_1_1_scanner_callback.html',1,'com::systemic::bluetoothle::Scanner']]],
  ['sendmessageandprocessresponseenumerator_624',['SendMessageAndProcessResponseEnumerator',['../class_systemic_1_1_unity_1_1_pixels_1_1_pixel_1_1_send_message_and_process_response_enumerator.html',1,'Systemic::Unity::Pixels::Pixel']]],
  ['sendmessageandprocessresponsewithvalueenumerator_625',['SendMessageAndProcessResponseWithValueEnumerator',['../class_systemic_1_1_unity_1_1_pixels_1_1_pixel_1_1_send_message_and_process_response_with_value_enumerator.html',1,'Systemic::Unity::Pixels::Pixel']]],
  ['sendmessageandwaitforresponseenumerator_626',['SendMessageAndWaitForResponseEnumerator',['../class_systemic_1_1_unity_1_1_pixels_1_1_pixel_1_1_send_message_and_wait_for_response_enumerator.html',1,'Systemic::Unity::Pixels::Pixel']]],
  ['service_627',['Service',['../class_systemic_1_1_bluetooth_l_e_1_1_service.html',1,'Systemic::BluetoothLE']]],
  ['setallledstocolor_628',['SetAllLEDsToColor',['../class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_all_l_e_ds_to_color.html',1,'Systemic::Unity::Pixels::Messages']]],
  ['setbattlestate_629',['SetBattleState',['../class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_battle_state.html',1,'Systemic::Unity::Pixels::Messages']]],
  ['setcurrentbehavior_630',['SetCurrentBehavior',['../class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_current_behavior.html',1,'Systemic::Unity::Pixels::Messages']]],
  ['setcurrentbehaviorack_631',['SetCurrentBehaviorAck',['../class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_current_behavior_ack.html',1,'Systemic::Unity::Pixels::Messages']]],
  ['setdesignandcolor_632',['SetDesignAndColor',['../class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_design_and_color.html',1,'Systemic::Unity::Pixels::Messages']]],
  ['setdesignandcolorack_633',['SetDesignAndColorAck',['../class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_design_and_color_ack.html',1,'Systemic::Unity::Pixels::Messages']]],
  ['setledanimstate_634',['SetLEDAnimState',['../class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_l_e_d_anim_state.html',1,'Systemic::Unity::Pixels::Messages']]],
  ['setname_635',['SetName',['../class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_name.html',1,'Systemic::Unity::Pixels::Messages']]],
  ['setnameack_636',['SetNameAck',['../class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_name_ack.html',1,'Systemic::Unity::Pixels::Messages']]],
  ['setstandardstate_637',['SetStandardState',['../class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_standard_state.html',1,'Systemic::Unity::Pixels::Messages']]],
  ['sgblecentralmanagerdelegate_638',['SGBleCentralManagerDelegate',['../interface_s_g_ble_central_manager_delegate.html',1,'']]],
  ['sgbleperipheralqueue_639',['SGBlePeripheralQueue',['../interface_s_g_ble_peripheral_queue.html',1,'']]],
  ['sgblerequest_640',['SGBleRequest',['../interface_s_g_ble_request.html',1,'']]],
  ['stopanimation_641',['StopAnimation',['../class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_stop_animation.html',1,'Systemic::Unity::Pixels::Messages']]]
];
