var searchData=
[
  ['scannedperipheral_528',['ScannedPeripheral',['../class_systemic_1_1_bluetooth_l_e_1_1_scanned_peripheral.html',1,'Systemic::BluetoothLE::ScannedPeripheral'],['../class_systemic_1_1_unity_1_1_bluetooth_l_e_1_1_scanned_peripheral.html',1,'Systemic.Unity.BluetoothLE.ScannedPeripheral']]],
  ['scanner_529',['Scanner',['../classcom_1_1systemic_1_1bluetoothle_1_1_scanner.html',1,'com.systemic.bluetoothle.Scanner'],['../class_systemic_1_1_bluetooth_l_e_1_1_scanner.html',1,'Systemic::BluetoothLE::Scanner']]],
  ['scannercallback_530',['ScannerCallback',['../interfacecom_1_1systemic_1_1bluetoothle_1_1_scanner_1_1_scanner_callback.html',1,'com::systemic::bluetoothle::Scanner']]],
  ['sendmessageandwaitforresponseenumerator_531',['SendMessageAndWaitForResponseEnumerator',['../class_systemic_1_1_unity_1_1_pixels_1_1_pixel_1_1_send_message_and_wait_for_response_enumerator.html',1,'Systemic::Unity::Pixels::Pixel']]],
  ['service_532',['Service',['../class_systemic_1_1_bluetooth_l_e_1_1_service.html',1,'Systemic::BluetoothLE']]],
  ['setallledstocolor_533',['SetAllLEDsToColor',['../class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_all_l_e_ds_to_color.html',1,'Systemic::Unity::Pixels::Messages']]],
  ['setbattlestate_534',['SetBattleState',['../class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_battle_state.html',1,'Systemic::Unity::Pixels::Messages']]],
  ['setcurrentbehavior_535',['SetCurrentBehavior',['../class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_current_behavior.html',1,'Systemic::Unity::Pixels::Messages']]],
  ['setcurrentbehaviorack_536',['SetCurrentBehaviorAck',['../class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_current_behavior_ack.html',1,'Systemic::Unity::Pixels::Messages']]],
  ['setdesignandcolor_537',['SetDesignAndColor',['../class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_design_and_color.html',1,'Systemic::Unity::Pixels::Messages']]],
  ['setdesignandcolorack_538',['SetDesignAndColorAck',['../class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_design_and_color_ack.html',1,'Systemic::Unity::Pixels::Messages']]],
  ['setledanimstate_539',['SetLEDAnimState',['../class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_l_e_d_anim_state.html',1,'Systemic::Unity::Pixels::Messages']]],
  ['setname_540',['SetName',['../class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_name.html',1,'Systemic::Unity::Pixels::Messages']]],
  ['setnameack_541',['SetNameAck',['../class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_name_ack.html',1,'Systemic::Unity::Pixels::Messages']]],
  ['setstandardstate_542',['SetStandardState',['../class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_set_standard_state.html',1,'Systemic::Unity::Pixels::Messages']]],
  ['sgblecentralmanagerdelegate_543',['SGBleCentralManagerDelegate',['../interface_s_g_ble_central_manager_delegate.html',1,'']]],
  ['sgbleperipheralqueue_544',['SGBlePeripheralQueue',['../interface_s_g_ble_peripheral_queue.html',1,'']]],
  ['sgblerequest_545',['SGBleRequest',['../interface_s_g_ble_request.html',1,'']]],
  ['stopanimation_546',['StopAnimation',['../class_systemic_1_1_unity_1_1_pixels_1_1_messages_1_1_stop_animation.html',1,'Systemic::Unity::Pixels::Messages']]]
];
